#!/bin/sh
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
# Vérification des régressions (ou améliorations) après un test complet
# Checking regressions (or improvements) in the results of full tests
#
# See the license in the POD documentation below.
#

export dir_res=results

export ref=$1
export base=$2
echo $ref $base

cd results

for i in 324 basic dyn-short egg list-short meta multi other parallel parallel-1 parallel-2
do
    echo -------------
    echo $i
    echo -------------
    diff $ref-$i $base-$i
done

exit;

=begin POD

=encoding utf8

=head1 NAME

check-full-test.sh -- Comparing the results of a full test with those of a reference full test

=head1  DESCRIPTION

Run Unix's C<diff> on the files generated by C<full-test.sh>.

=head1 USAGE

Regression tests:

  sh full-test.sh test1
  #
  # make a few modifications in program C<schema-check.pl> or in schema files C<schema/product*.yaml>
  #
  sh full-test.sh test2
  sh check-full-test.sh test1 test2

=head2 Parameters

The two parameters are the basenames for the listing files.
The first parameter is the basename for the reference files
and the second parameter is the basename for the new files.

=head1 COPYRIGHT and LICENSE

Copyright (C) 2024, Jean Forget, all rights reserved

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

=end POD
